# Site settings
title: GLEAM DP
author: GLEAM DP Development Team
email: johannes.zauner@tum.de
url: "https://tscnlab.github.io/GLEAM-dp/"
baseurl: "/glc_dp_viewer"

# SOCIAL PROFILES
social:
  github: tscnlab/glc_dp_viewer


# Theme
theme: minima
remote_theme: tdwg/petridish
github_edit: true
logo: assets/glc_logo.png

# Build settings
repository: tscnlab/glc_dp_viewer # Required so Jekyll on GitHub Actions can access repo metadata
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
